---
title: "Periwinkle Children's Therapy"
paginate: 20
address: 1397 N Biztown Loop<br> Hayden, Idaho 83835
phone: (208) 762-3502
fax: (888) 310-4824
programs:
    - title: Speech
      summary: Speech-Language Therapy
      url: "speech-language-therapy.html"
    - title: Occupational
      summary: Occupational Therapy
      url: "occupational-therapy.html"
    - title: Physical
      summary: Physical Therapy
      url: "physical-therapy.html"
news:
    - title: "We're working hard to update our website"
      url: http://www.facebook.com/PeriwinkleTherapy/posts/414822768610204
    - title: Ut malesuada suscipit augue accumsan rutrum
      url: "#"
    - title: Suspendisse non est ut augue dapibus pulvinar
      url: "#"
events:
    - title: At faucibus nulla placerat ac
      url: "#"
      date: March 1st
    - title: Sed iaculis convallis
      url: "#"
      date: April 6th
    - title: Lacus eros, luctus a faucibus vitae
      url: "#"
      date: May 18th
sidebar-testimonial:
    quote: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."
    attribution: John Doe
testimonials:
    - quote: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."
      attribution: John Doe
      title: Testimonial 1
      url: "#"
    - quote: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas."
      attribution: John Doe
      title: Testimonial 2
      url: "#"
--- 